import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button"
import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <div className="flex flex-col  justify-center h-screen gap-4">
            <div className="min-h-screen ">
              <header className="bg-gray-900 shadow-lg">
                <div className="container mx-auto px-6 py-4">
                  <div className="flex items-center justify-between">
                    <Link href={'/'} className="flex items-center space-x-2">
                      <div className="w-8 h-8 bg-white rounded-lg flex items-center justify-center">
                        <span className="text-red-500 font-bold text-lg">M</span>
                      </div>
                      <h1 className="text-white text-2xl font-bold">marketilize</h1>
                    </Link>
                    <Button
                      variant="secondary"
                      className="bg-white text-red-600 hover:bg-gray-100 font-semibold px-6 shadow-md transition-all duration-200 hover:shadow-lg"
                    >
                      Redes sociais
                    </Button>
                  </div>
                </div>
              </header>
              <main className="min-h-screen ">
              {children}
              </main>
              <footer className="bg-gray-900 text-white min-w-full">
                <div className="container mx-auto px-6 py-16">
                  <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
                    <div className="md:col-span-2">
                      <div className="flex items-center space-x-2 mb-4">
                        <div className="w-8 h-8 bg-red-500 rounded-lg flex items-center justify-center">
                          <span className="text-white font-bold text-lg">M</span>
                        </div>
                        <h3 className="text-2xl font-bold">marketilize</h3>
                      </div>
                      <p className="text-gray-400 mb-6 max-w-md">
                        Sua fonte confiável para estratégias de marketing digital, desenvolvimento web e crescimento de negócios
                        online.
                      </p>
                      <div className="flex space-x-4">
                        <Button
                          size="sm"
                          variant="outline"
                          className="border-gray-600 text-gray-300 hover:bg-red-500 hover:border-red-500 bg-transparent"
                        >
                          Facebook
                        </Button>
                        <Button
                          size="sm"
                          variant="outline"
                          className="border-gray-600 text-gray-300 hover:bg-red-500 hover:border-red-500 bg-transparent"
                        >
                          Twitter
                        </Button>
                        <Button
                          size="sm"
                          variant="outline"
                          className="border-gray-600 text-gray-300 hover:bg-red-500 hover:border-red-500 bg-transparent"
                        >
                          LinkedIn
                        </Button>
                      </div>
                    </div>

                    <div>
                      <h4 className="font-semibold mb-4">Categorias</h4>
                      <ul className="space-y-2 text-gray-400">
                        <li>
                          <a href="#" className="hover:text-red-400 transition-colors">
                            Marketing Digital
                          </a>
                        </li>
                        <li>
                          <a href="#" className="hover:text-red-400 transition-colors">
                            Desenvolvimento Web
                          </a>
                        </li>
                        <li>
                          <a href="#" className="hover:text-red-400 transition-colors">
                            SEO
                          </a>
                        </li>
                        <li>
                          <a href="#" className="hover:text-red-400 transition-colors">
                            Redes Sociais
                          </a>
                        </li>
                      </ul>
                    </div>

                    <div>
                      <h4 className="font-semibold mb-4">Empresa</h4>
                      <ul className="space-y-2 text-gray-400">
                        <li>
                          <a href="#" className="hover:text-red-400 transition-colors">
                            Sobre
                          </a>
                        </li>
                        <li>
                          <a href="#" className="hover:text-red-400 transition-colors">
                            Contato
                          </a>
                        </li>
                        <li>
                          <a href="#" className="hover:text-red-400 transition-colors">
                            Política de Privacidade
                          </a>
                        </li>
                        <li>
                          <a href="#" className="hover:text-red-400 transition-colors">
                            Termos de Uso
                          </a>
                        </li>
                      </ul>
                    </div>
                  </div>

                  <div className="border-t border-gray-800 mt-12 pt-8 text-center text-gray-400">
                    <p>&copy; 2024 Marketilize. Todos os direitos reservados.</p>
                  </div>
                </div>
              </footer>
            </div>
          </div>
      </body>
    </html>
  );
}
